version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      REDIS_URL: redis://redis:6379
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - build:/app/_build
      - deps:/app/deps

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - 6379:6379
    volumes:
      - redis:/data

networks:
  default:
    name: rinha-elixir
    driver: bridge

volumes:
  pg-data:
  build:
  deps:
  redis:
