version: "3.9"
services:
  app:
    build:
      context: .
      target: release
    depends_on:
      - db
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/rinha_backend_elixir_dev
      SECRET_KEY_BASE: 1Syx0lXQyk/14OAbwdLwFr7a7loSGc8z/ImnU+93HRdSSO2r31Y8gccUURgkPEd0
    ports:
      - 4000:4000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

networks:
  default:
    name: rinha-elixir
    driver: bridge

volumes:
  pg-data:
